# Changes here will be overwritten by Copier
_commit: v0.5.1
_src_path: gl:openscm/copier-basic-python-repository
email: zebedee.nicholls@climate-resource.con
local_src: true
name: Zebedee Nicholls
notebooks: false
package_manager: uv
project_description_short: Prototype of use of GitHub forms
project_url: https://github.com/znichollscr/github-forms-scratch
